export enum EmojiType {
    People = 'People',
    Foods = 'Foods',
    Nature = 'Nature',
    Symbols = 'Symbols',
}
export interface EmojiItem {
    emoji: string;
    type: EmojiType;
    label: string;
    shorts: string[];
}
export const PeopleEmoji: EmojiItem[] = [
    { emoji: '😀', type: EmojiType.People, label: 'Grinning Face', shorts: ['grinning'] },
    { emoji: '😃', type: EmojiType.People, label: 'Grinning Face With Big Eyes', shorts: ['smiley'] },
    { emoji: '😄', type: EmojiType.People, label: 'Grinning Face With Smiling Eyes', shorts: ['smile'] },
    { emoji: '😁', type: EmojiType.People, label: 'Beaming Face With Smiling Eyes', shorts: ['grin'] },
    { emoji: '😆', type: EmojiType.People, label: 'Grinning Squinting Face', shorts: ['laughing', 'satisfied'] },
    { emoji: '😅', type: EmojiType.People, label: 'Grinning Face With Sweat', shorts: ['sweat_smile'] },
    { emoji: '🤣', type: EmojiType.People, label: 'Rolling on the Floor Laughing', shorts: [] },
    { emoji: '😂', type: EmojiType.People, label: 'Face With Tears of Joy', shorts: ['joy'] },
    { emoji: '🙂', type: EmojiType.People, label: 'Slightly Smiling Face', shorts: [] },
    { emoji: '🙃', type: EmojiType.People, label: 'Upside-Down Face', shorts: [] },
    { emoji: '😉', type: EmojiType.People, label: 'Winking Face', shorts: ['wink'] },
    { emoji: '😊', type: EmojiType.People, label: 'Smiling Face With Smiling Eyes', shorts: ['blush'] },
    { emoji: '😇', type: EmojiType.People, label: 'Smiling Face With Halo', shorts: ['innocent'] },
    { emoji: '😍', type: EmojiType.People, label: 'Smiling Face With Heart-Eyes', shorts: ['heart_eyes'] },
    { emoji: '🤩', type: EmojiType.People, label: 'Star-Struck', shorts: [] },
    { emoji: '😘', type: EmojiType.People, label: 'Face Blowing a Kiss', shorts: ['kissing_heart'] },
    { emoji: '😗', type: EmojiType.People, label: 'Kissing Face', shorts: ['kissing'] },
    { emoji: '😚', type: EmojiType.People, label: 'Kissing Face With Closed Eyes', shorts: ['kissing_closed_eyes'] },
    { emoji: '😙', type: EmojiType.People, label: 'Kissing Face With Smiling Eyes', shorts: ['kissing_smiling_eyes'] },
    { emoji: '😋', type: EmojiType.People, label: 'Face Savoring Food', shorts: ['yum'] },
    { emoji: '😛', type: EmojiType.People, label: 'Face With Tongue', shorts: ['stuck_out_tongue'] },
    {
        emoji: '😜',
        type: EmojiType.People,
        label: 'Winking Face With Tongue',
        shorts: ['stuck_out_tongue_winking_eye'],
    },
    { emoji: '🤪', type: EmojiType.People, label: 'Zany Face', shorts: [] },
    {
        emoji: '😝',
        type: EmojiType.People,
        label: 'Squinting Face With Tongue',
        shorts: ['stuck_out_tongue_closed_eyes'],
    },
    { emoji: '🤑', type: EmojiType.People, label: 'Money-Mouth Face', shorts: [] },
    { emoji: '🤗', type: EmojiType.People, label: 'Hugging Face', shorts: [] },
    { emoji: '🤭', type: EmojiType.People, label: 'Face With Hand Over Mouth', shorts: [] },
    { emoji: '🤫', type: EmojiType.People, label: 'Shushing Face', shorts: [] },
    { emoji: '🤔', type: EmojiType.People, label: 'Thinking Face', shorts: [] },
    { emoji: '🤐', type: EmojiType.People, label: 'Zipper-Mouth Face', shorts: [] },
    { emoji: '🤨', type: EmojiType.People, label: 'Face With Raised Eyebrow', shorts: [] },
    { emoji: '😐', type: EmojiType.People, label: 'Neutral Face', shorts: ['neutral_face'] },
    { emoji: '😑', type: EmojiType.People, label: 'Expressionless Face', shorts: ['expressionless'] },
    { emoji: '😶', type: EmojiType.People, label: 'Face Without Mouth', shorts: ['no_mouth'] },
    { emoji: '😏', type: EmojiType.People, label: 'Smirking Face', shorts: ['smirk'] },
    { emoji: '😒', type: EmojiType.People, label: 'Unamused Face', shorts: ['unamused'] },
    { emoji: '🙄', type: EmojiType.People, label: 'Face With Rolling Eyes', shorts: [] },
    { emoji: '😬', type: EmojiType.People, label: 'Grimacing Face', shorts: ['grimacing'] },
    { emoji: '🤥', type: EmojiType.People, label: 'Lying Face', shorts: [] },
    { emoji: '😌', type: EmojiType.People, label: 'Relieved Face', shorts: ['relieved'] },
    { emoji: '😔', type: EmojiType.People, label: 'Pensive Face', shorts: ['pensive'] },
    { emoji: '😪', type: EmojiType.People, label: 'Sleepy Face', shorts: ['sleepy'] },
    { emoji: '🤤', type: EmojiType.People, label: 'Drooling Face', shorts: [] },
    { emoji: '😴', type: EmojiType.People, label: 'Sleeping Face', shorts: ['sleeping'] },
    { emoji: '😷', type: EmojiType.People, label: 'Face With Medical Mask', shorts: ['mask'] },
    { emoji: '🤒', type: EmojiType.People, label: 'Face With Thermometer', shorts: [] },
    { emoji: '🤕', type: EmojiType.People, label: 'Face With Head-Bandage', shorts: [] },
    { emoji: '🤢', type: EmojiType.People, label: 'Nauseated Face', shorts: [] },
    { emoji: '🤮', type: EmojiType.People, label: 'Face Vomiting', shorts: [] },
    { emoji: '🤧', type: EmojiType.People, label: 'Sneezing Face', shorts: [] },
    { emoji: '😵', type: EmojiType.People, label: 'Dizzy Face', shorts: ['dizzy_face'] },
    { emoji: '🤯', type: EmojiType.People, label: 'Exploding Head', shorts: [] },
    { emoji: '🤠', type: EmojiType.People, label: 'Cowboy Hat Face', shorts: [] },
    { emoji: '😎', type: EmojiType.People, label: 'Smiling Face With Sunglasses', shorts: ['sunglasses'] },
    { emoji: '🤓', type: EmojiType.People, label: 'Nerd Face', shorts: [] },
    { emoji: '🧐', type: EmojiType.People, label: 'Face With Monocle', shorts: [] },
    { emoji: '😕', type: EmojiType.People, label: 'Confused Face', shorts: ['confused'] },
    { emoji: '😟', type: EmojiType.People, label: 'Worried Face', shorts: ['worried'] },
    { emoji: '🙁', type: EmojiType.People, label: 'Slightly Frowning Face', shorts: [] },
    { emoji: '☹️', type: EmojiType.People, label: 'rowning Face', shorts: [] },
    { emoji: '😮', type: EmojiType.People, label: 'Face With Open Mouth', shorts: ['open_mouth'] },
    { emoji: '😯', type: EmojiType.People, label: 'Hushed Face', shorts: ['hushed'] },
    { emoji: '😲', type: EmojiType.People, label: 'Astonished Face', shorts: ['astonished'] },
    { emoji: '😳', type: EmojiType.People, label: 'Flushed Face', shorts: ['flushed'] },
    { emoji: '😦', type: EmojiType.People, label: 'Frowning Face With Open Mouth', shorts: ['frowning'] },
    { emoji: '😧', type: EmojiType.People, label: 'Anguished Face', shorts: ['anguished'] },
    { emoji: '😨', type: EmojiType.People, label: 'Fearful Face', shorts: ['fearful'] },
    { emoji: '😰', type: EmojiType.People, label: 'Anxious Face With Sweat', shorts: ['cold_sweat'] },
    { emoji: '😥', type: EmojiType.People, label: 'Sad but Relieved Face', shorts: ['disappointed_relieved'] },
    { emoji: '😢', type: EmojiType.People, label: 'Crying Face', shorts: ['cry'] },
    { emoji: '😭', type: EmojiType.People, label: 'Loudly Crying Face', shorts: ['sob'] },
    { emoji: '😱', type: EmojiType.People, label: 'Face Screaming in Fear', shorts: ['scream'] },
    { emoji: '😖', type: EmojiType.People, label: 'Confounded Face', shorts: ['confounded'] },
    { emoji: '😣', type: EmojiType.People, label: 'Persevering Face', shorts: ['persevere'] },
    { emoji: '😞', type: EmojiType.People, label: 'Disappointed Face', shorts: ['disappointed'] },
    { emoji: '😓', type: EmojiType.People, label: 'Downcast Face With Sweat', shorts: ['sweat'] },
    { emoji: '😩', type: EmojiType.People, label: 'Weary Face', shorts: ['weary'] },
    { emoji: '😫', type: EmojiType.People, label: 'Tired Face', shorts: ['tired_face'] },
    { emoji: '😤', type: EmojiType.People, label: 'Face With Steam From Nose', shorts: ['triumph'] },
    { emoji: '😡', type: EmojiType.People, label: 'Pouting Face', shorts: ['rage'] },
    { emoji: '😠', type: EmojiType.People, label: 'Angry Face', shorts: ['angry'] },
    { emoji: '🤬', type: EmojiType.People, label: 'Face With Symbols on Mouth', shorts: [] },
    { emoji: '😈', type: EmojiType.People, label: 'Smiling Face With Horns', shorts: ['smiling_imp'] },
    { emoji: '👿', type: EmojiType.People, label: 'Angry Face With Horns', shorts: ['imp'] },
    { emoji: '💀', type: EmojiType.People, label: 'Skull', shorts: ['skull'] },
    { emoji: '☠️', type: EmojiType.People, label: 'kull and Crossbones', shorts: [] },
    { emoji: '💩', type: EmojiType.People, label: 'Pile of Poo', shorts: ['hankey', 'poop', 'shit'] },
    { emoji: '🤡', type: EmojiType.People, label: 'Clown Face', shorts: [] },
    { emoji: '👹', type: EmojiType.People, label: 'Ogre', shorts: ['japanese_ogre'] },
    { emoji: '👺', type: EmojiType.People, label: 'Goblin', shorts: ['japanese_goblin'] },
    { emoji: '👻', type: EmojiType.People, label: 'Ghost', shorts: ['ghost'] },
    { emoji: '👽', type: EmojiType.People, label: 'Alien', shorts: ['alien'] },
    { emoji: '👾', type: EmojiType.People, label: 'Alien Monster', shorts: ['space_invader'] },
    { emoji: '🤖', type: EmojiType.People, label: 'Robot Face', shorts: [] },
    { emoji: '😺', type: EmojiType.People, label: 'Grinning Cat Face', shorts: ['smiley_cat'] },
    { emoji: '😸', type: EmojiType.People, label: 'Grinning Cat Face With Smiling Eyes', shorts: ['smile_cat'] },
    { emoji: '😹', type: EmojiType.People, label: 'Cat Face With Tears of Joy', shorts: ['joy_cat'] },
    { emoji: '😻', type: EmojiType.People, label: 'Smiling Cat Face With Heart-Eyes', shorts: ['heart_eyes_cat'] },
    { emoji: '😼', type: EmojiType.People, label: 'Cat Face With Wry Smile', shorts: ['smirk_cat'] },
    { emoji: '😽', type: EmojiType.People, label: 'Kissing Cat Face', shorts: ['kissing_cat'] },
    { emoji: '🙀', type: EmojiType.People, label: 'Weary Cat Face', shorts: ['scream_cat'] },
    { emoji: '😿', type: EmojiType.People, label: 'Crying Cat Face', shorts: ['crying_cat_face'] },
    { emoji: '😾', type: EmojiType.People, label: 'Pouting Cat Face', shorts: ['pouting_cat'] },
    { emoji: '💋', type: EmojiType.People, label: 'Kiss Mark', shorts: ['kiss'] },
    { emoji: '👋', type: EmojiType.People, label: 'Waving Hand', shorts: ['wave'] },
    { emoji: '🤚', type: EmojiType.People, label: 'Raised Back of Hand', shorts: [] },
    { emoji: '🖐️', type: EmojiType.People, label: 'Hand With Fingers Splayed', shorts: [] },
    { emoji: '✋', type: EmojiType.People, label: 'aised Hand', shorts: ['hand', 'raised_hand'] },
    { emoji: '🖖', type: EmojiType.People, label: 'Vulcan Salute', shorts: [] },
    { emoji: '👌', type: EmojiType.People, label: 'OK Hand', shorts: ['ok_hand'] },
    { emoji: '✌️', type: EmojiType.People, label: 'ictory Hand', shorts: ['v'] },
    { emoji: '🤞', type: EmojiType.People, label: 'Crossed Fingers', shorts: [] },
    { emoji: '🤟', type: EmojiType.People, label: 'Love-You Gesture', shorts: [] },
    { emoji: '🤘', type: EmojiType.People, label: 'Sign of the Horns', shorts: [] },
    { emoji: '🤙', type: EmojiType.People, label: 'Call Me Hand', shorts: [] },
    { emoji: '👈', type: EmojiType.People, label: 'Backhand Index Pointing Left', shorts: ['point_left'] },
    { emoji: '👉', type: EmojiType.People, label: 'Backhand Index Pointing Right', shorts: ['point_right'] },
    { emoji: '👆', type: EmojiType.People, label: 'Backhand Index Pointing Up', shorts: ['point_up_2'] },
    { emoji: '🖕', type: EmojiType.People, label: 'Middle Finger', shorts: [] },
    { emoji: '👇', type: EmojiType.People, label: 'Backhand Index Pointing Down', shorts: ['point_down'] },
    { emoji: '☝️', type: EmojiType.People, label: 'ndex Pointing Up', shorts: ['point_up'] },
    { emoji: '👍', type: EmojiType.People, label: 'Thumbs Up', shorts: ['+1', 'thumbsup'] },
    { emoji: '👎', type: EmojiType.People, label: 'Thumbs Down', shorts: ['-1', 'thumbsdown'] },
    { emoji: '✊', type: EmojiType.People, label: 'aised Fist', shorts: ['fist'] },
    { emoji: '👊', type: EmojiType.People, label: 'Oncoming Fist', shorts: ['facepunch', 'punch'] },
    { emoji: '🤛', type: EmojiType.People, label: 'Left-Facing Fist', shorts: [] },
    { emoji: '🤜', type: EmojiType.People, label: 'Right-Facing Fist', shorts: [] },
    { emoji: '👏', type: EmojiType.People, label: 'Clapping Hands', shorts: ['clap'] },
    { emoji: '🙌', type: EmojiType.People, label: 'Raising Hands', shorts: ['raised_hands'] },
    { emoji: '👐', type: EmojiType.People, label: 'Open Hands', shorts: ['open_hands'] },
    { emoji: '🤲', type: EmojiType.People, label: 'Palms Up Together', shorts: [] },
    { emoji: '🤝', type: EmojiType.People, label: 'Handshake', shorts: [] },
    { emoji: '🙏', type: EmojiType.People, label: 'Folded Hands', shorts: ['pray'] },
];

export const NatureEmoji: EmojiItem[] = [
    { emoji: '🙈', type: EmojiType.Nature, label: 'See-No-Evil Monkey', shorts: ['see_no_evil'] },
    { emoji: '🙉', type: EmojiType.Nature, label: 'Hear-No-Evil Monkey', shorts: ['hear_no_evil'] },
    { emoji: '🙊', type: EmojiType.Nature, label: 'Speak-No-Evil Monkey', shorts: ['speak_no_evil'] },
    { emoji: '💥', type: EmojiType.Nature, label: 'Collision', shorts: ['boom', 'collision'] },
    { emoji: '💫', type: EmojiType.Nature, label: 'Dizzy', shorts: ['dizzy'] },
    { emoji: '💦', type: EmojiType.Nature, label: 'Sweat Droplets', shorts: ['sweat_drops'] },
    { emoji: '💨', type: EmojiType.Nature, label: 'Dashing Away', shorts: ['dash'] },
    { emoji: '🐵', type: EmojiType.Nature, label: 'Monkey Face', shorts: ['monkey_face'] },
    { emoji: '🐒', type: EmojiType.Nature, label: 'Monkey', shorts: ['monkey'] },
    { emoji: '🦍', type: EmojiType.Nature, label: 'Gorilla', shorts: [] },
    { emoji: '🐶', type: EmojiType.Nature, label: 'Dog Face', shorts: ['dog'] },
    { emoji: '🐕', type: EmojiType.Nature, label: 'Dog', shorts: ['dog2'] },
    { emoji: '🐩', type: EmojiType.Nature, label: 'Poodle', shorts: ['poodle'] },
    { emoji: '🐺', type: EmojiType.Nature, label: 'Wolf Face', shorts: ['wolf'] },
    { emoji: '🦊', type: EmojiType.Nature, label: 'Fox Face', shorts: [] },
    { emoji: '🐱', type: EmojiType.Nature, label: 'Cat Face', shorts: ['cat'] },
    { emoji: '🐈', type: EmojiType.Nature, label: 'Cat', shorts: ['cat2'] },
    { emoji: '🦁', type: EmojiType.Nature, label: 'Lion Face', shorts: [] },
    { emoji: '🐯', type: EmojiType.Nature, label: 'Tiger Face', shorts: ['tiger'] },
    { emoji: '🐅', type: EmojiType.Nature, label: 'Tiger', shorts: ['tiger2'] },
    { emoji: '🐆', type: EmojiType.Nature, label: 'Leopard', shorts: ['leopard'] },
    { emoji: '🐴', type: EmojiType.Nature, label: 'Horse Face', shorts: ['horse'] },
    { emoji: '🐎', type: EmojiType.Nature, label: 'Horse', shorts: ['racehorse'] },
    { emoji: '🦄', type: EmojiType.Nature, label: 'Unicorn Face', shorts: [] },
    { emoji: '🦓', type: EmojiType.Nature, label: 'Zebra', shorts: [] },
    { emoji: '🐮', type: EmojiType.Nature, label: 'Cow Face', shorts: ['cow'] },
    { emoji: '🐂', type: EmojiType.Nature, label: 'Ox', shorts: ['ox'] },
    { emoji: '🐃', type: EmojiType.Nature, label: 'Water Buffalo', shorts: ['water_buffalo'] },
    { emoji: '🐄', type: EmojiType.Nature, label: 'Cow', shorts: ['cow2'] },
    { emoji: '🐷', type: EmojiType.Nature, label: 'Pig Face', shorts: ['pig'] },
    { emoji: '🐖', type: EmojiType.Nature, label: 'Pig', shorts: ['pig2'] },
    { emoji: '🐗', type: EmojiType.Nature, label: 'Boar', shorts: ['boar'] },
    { emoji: '🐽', type: EmojiType.Nature, label: 'Pig Nose', shorts: ['pig_nose'] },
    { emoji: '🐏', type: EmojiType.Nature, label: 'Ram', shorts: ['ram'] },
    { emoji: '🐑', type: EmojiType.Nature, label: 'Ewe', shorts: ['sheep'] },
    { emoji: '🐐', type: EmojiType.Nature, label: 'Goat', shorts: ['goat'] },
    { emoji: '🐪', type: EmojiType.Nature, label: 'Camel', shorts: ['dromedary_camel'] },
    { emoji: '🐫', type: EmojiType.Nature, label: 'Two-Hump Camel', shorts: ['camel'] },
    { emoji: '🦒', type: EmojiType.Nature, label: 'Giraffe', shorts: [] },
    { emoji: '🐘', type: EmojiType.Nature, label: 'Elephant', shorts: ['elephant'] },
    { emoji: '🦏', type: EmojiType.Nature, label: 'Rhinoceros', shorts: [] },
    { emoji: '🐭', type: EmojiType.Nature, label: 'Mouse Face', shorts: ['mouse'] },
    { emoji: '🐁', type: EmojiType.Nature, label: 'Mouse', shorts: ['mouse2'] },
    { emoji: '🐀', type: EmojiType.Nature, label: 'Rat', shorts: ['rat'] },
    { emoji: '🐹', type: EmojiType.Nature, label: 'Hamster Face', shorts: ['hamster'] },
    { emoji: '🐰', type: EmojiType.Nature, label: 'Rabbit Face', shorts: ['rabbit'] },
    { emoji: '🐇', type: EmojiType.Nature, label: 'Rabbit', shorts: ['rabbit2'] },
    { emoji: '🐿️', type: EmojiType.Nature, label: 'Chipmunk', shorts: [] },
    { emoji: '🦔', type: EmojiType.Nature, label: 'Hedgehog', shorts: [] },
    { emoji: '🦇', type: EmojiType.Nature, label: 'Bat', shorts: [] },
    { emoji: '🐻', type: EmojiType.Nature, label: 'Bear Face', shorts: ['bear'] },
    { emoji: '🐨', type: EmojiType.Nature, label: 'Koala', shorts: ['koala'] },
    { emoji: '🐼', type: EmojiType.Nature, label: 'Panda Face', shorts: ['panda_face'] },
    { emoji: '🐾', type: EmojiType.Nature, label: 'Paw Prints', shorts: ['feet', 'paw_prints'] },
    { emoji: '🦃', type: EmojiType.Nature, label: 'Turkey', shorts: [] },
    { emoji: '🐔', type: EmojiType.Nature, label: 'Chicken', shorts: ['chicken'] },
    { emoji: '🐓', type: EmojiType.Nature, label: 'Rooster', shorts: ['rooster'] },
    { emoji: '🐣', type: EmojiType.Nature, label: 'Hatching Chick', shorts: ['hatching_chick'] },
    { emoji: '🐤', type: EmojiType.Nature, label: 'Baby Chick', shorts: ['baby_chick'] },
    { emoji: '🐥', type: EmojiType.Nature, label: 'Front-Facing Baby Chick', shorts: ['hatched_chick'] },
    { emoji: '🐦', type: EmojiType.Nature, label: 'Bird', shorts: ['bird'] },
    { emoji: '🐧', type: EmojiType.Nature, label: 'Penguin', shorts: ['penguin'] },
    { emoji: '🕊️', type: EmojiType.Nature, label: 'Dove', shorts: [] },
    { emoji: '🦅', type: EmojiType.Nature, label: 'Eagle', shorts: [] },
    { emoji: '🦆', type: EmojiType.Nature, label: 'Duck', shorts: [] },
    { emoji: '🦉', type: EmojiType.Nature, label: 'Owl', shorts: [] },
    { emoji: '🐸', type: EmojiType.Nature, label: 'Frog Face', shorts: ['frog'] },
    { emoji: '🐊', type: EmojiType.Nature, label: 'Crocodile', shorts: ['crocodile'] },
    { emoji: '🐢', type: EmojiType.Nature, label: 'Turtle', shorts: ['turtle'] },
    { emoji: '🦎', type: EmojiType.Nature, label: 'Lizard', shorts: [] },
    { emoji: '🐍', type: EmojiType.Nature, label: 'Snake', shorts: ['snake'] },
    { emoji: '🐲', type: EmojiType.Nature, label: 'Dragon Face', shorts: ['dragon_face'] },
    { emoji: '🐉', type: EmojiType.Nature, label: 'Dragon', shorts: ['dragon'] },
    { emoji: '🦕', type: EmojiType.Nature, label: 'Sauropod', shorts: [] },
    { emoji: '🦖', type: EmojiType.Nature, label: 'T-Rex', shorts: [] },
    { emoji: '🐳', type: EmojiType.Nature, label: 'Spouting Whale', shorts: ['whale'] },
    { emoji: '🐋', type: EmojiType.Nature, label: 'Whale', shorts: ['whale2'] },
    { emoji: '🐬', type: EmojiType.Nature, label: 'Dolphin', shorts: ['dolphin', 'flipper'] },
    { emoji: '🐟', type: EmojiType.Nature, label: 'Fish', shorts: ['fish'] },
    { emoji: '🐠', type: EmojiType.Nature, label: 'Tropical Fish', shorts: ['tropical_fish'] },
    { emoji: '🐡', type: EmojiType.Nature, label: 'Blowfish', shorts: ['blowfish'] },
    { emoji: '🦈', type: EmojiType.Nature, label: 'Shark', shorts: [] },
    { emoji: '🐙', type: EmojiType.Nature, label: 'Octopus', shorts: ['octopus'] },
    { emoji: '🐚', type: EmojiType.Nature, label: 'Spiral Shell', shorts: ['shell'] },
    { emoji: '🐌', type: EmojiType.Nature, label: 'Snail', shorts: ['snail'] },
    { emoji: '🦋', type: EmojiType.Nature, label: 'Butterfly', shorts: [] },
    { emoji: '🐛', type: EmojiType.Nature, label: 'Bug', shorts: ['bug'] },
    { emoji: '🐜', type: EmojiType.Nature, label: 'Ant', shorts: ['ant'] },
    { emoji: '🐝', type: EmojiType.Nature, label: 'Honeybee', shorts: ['bee', 'honeybee'] },
    { emoji: '🐞', type: EmojiType.Nature, label: 'Lady Beetle', shorts: ['beetle'] },
    { emoji: '🦗', type: EmojiType.Nature, label: 'Cricket', shorts: [] },
    { emoji: '🕷️', type: EmojiType.Nature, label: 'Spider', shorts: [] },
    { emoji: '🕸️', type: EmojiType.Nature, label: 'Spider Web', shorts: [] },
    { emoji: '🦂', type: EmojiType.Nature, label: 'Scorpion', shorts: [] },
    { emoji: '💐', type: EmojiType.Nature, label: 'Bouquet', shorts: ['bouquet'] },
    { emoji: '🌸', type: EmojiType.Nature, label: 'Cherry Blossom', shorts: ['cherry_blossom'] },
    { emoji: '💮', type: EmojiType.Nature, label: 'White Flower', shorts: ['white_flower'] },
    { emoji: '🏵️', type: EmojiType.Nature, label: 'Rosette', shorts: [] },
    { emoji: '🌹', type: EmojiType.Nature, label: 'Rose', shorts: ['rose'] },
    { emoji: '🥀', type: EmojiType.Nature, label: 'Wilted Flower', shorts: [] },
    { emoji: '🌺', type: EmojiType.Nature, label: 'Hibiscus', shorts: ['hibiscus'] },
    { emoji: '🌻', type: EmojiType.Nature, label: 'Sunflower', shorts: ['sunflower'] },
    { emoji: '🌼', type: EmojiType.Nature, label: 'Blossom', shorts: ['blossom'] },
    { emoji: '🌷', type: EmojiType.Nature, label: 'Tulip', shorts: ['tulip'] },
    { emoji: '🌱', type: EmojiType.Nature, label: 'Seedling', shorts: ['seedling'] },
    { emoji: '🌲', type: EmojiType.Nature, label: 'Evergreen Tree', shorts: ['evergreen_tree'] },
    { emoji: '🌳', type: EmojiType.Nature, label: 'Deciduous Tree', shorts: ['deciduous_tree'] },
    { emoji: '🌴', type: EmojiType.Nature, label: 'Palm Tree', shorts: ['palm_tree'] },
    { emoji: '🌵', type: EmojiType.Nature, label: 'Cactus', shorts: ['cactus'] },
    { emoji: '🌾', type: EmojiType.Nature, label: 'Sheaf of Rice', shorts: ['ear_of_rice'] },
    { emoji: '🌿', type: EmojiType.Nature, label: 'Herb', shorts: ['herb'] },
    { emoji: '☘️', type: EmojiType.Nature, label: 'hamrock', shorts: [] },
    { emoji: '🍀', type: EmojiType.Nature, label: 'Four Leaf Clover', shorts: ['four_leaf_clover'] },
    { emoji: '🍁', type: EmojiType.Nature, label: 'Maple Leaf', shorts: ['maple_leaf'] },
    { emoji: '🍂', type: EmojiType.Nature, label: 'Fallen Leaf', shorts: ['fallen_leaf'] },
    { emoji: '🍃', type: EmojiType.Nature, label: 'Leaf Fluttering in Wind', shorts: ['leaves'] },
    { emoji: '🍄', type: EmojiType.Nature, label: 'Mushroom', shorts: ['mushroom'] },
    { emoji: '🌰', type: EmojiType.Nature, label: 'Chestnut', shorts: ['chestnut'] },
    { emoji: '🦀', type: EmojiType.Nature, label: 'Crab', shorts: [] },
    { emoji: '🦐', type: EmojiType.Nature, label: 'Shrimp', shorts: [] },
    { emoji: '🦑', type: EmojiType.Nature, label: 'Squid', shorts: [] },
    { emoji: '🌍', type: EmojiType.Nature, label: 'Globe Showing Europe-Africa', shorts: ['earth_africa'] },
    { emoji: '🌎', type: EmojiType.Nature, label: 'Globe Showing Americas', shorts: ['earth_americas'] },
    { emoji: '🌏', type: EmojiType.Nature, label: 'Globe Showing Asia-Australia', shorts: ['earth_asia'] },
    { emoji: '🌐', type: EmojiType.Nature, label: 'Globe With Meridians', shorts: ['globe_with_meridians'] },
    { emoji: '🌑', type: EmojiType.Nature, label: 'New Moon', shorts: ['new_moon'] },
    { emoji: '🌒', type: EmojiType.Nature, label: 'Waxing Crescent Moon', shorts: ['waxing_crescent_moon'] },
    { emoji: '🌓', type: EmojiType.Nature, label: 'First Quarter Moon', shorts: ['first_quarter_moon'] },
    { emoji: '🌔', type: EmojiType.Nature, label: 'Waxing Gibbous Moon', shorts: ['moon', 'waxing_gibbous_moon'] },
    { emoji: '🌕', type: EmojiType.Nature, label: 'Full Moon', shorts: ['full_moon'] },
    { emoji: '🌖', type: EmojiType.Nature, label: 'Waning Gibbous Moon', shorts: ['waning_gibbous_moon'] },
    { emoji: '🌗', type: EmojiType.Nature, label: 'Last Quarter Moon', shorts: ['last_quarter_moon'] },
    { emoji: '🌘', type: EmojiType.Nature, label: 'Waning Crescent Moon', shorts: ['waning_crescent_moon'] },
    { emoji: '🌙', type: EmojiType.Nature, label: 'Crescent Moon', shorts: ['crescent_moon'] },
    { emoji: '🌚', type: EmojiType.Nature, label: 'New Moon Face', shorts: ['new_moon_with_face'] },
    { emoji: '🌛', type: EmojiType.Nature, label: 'First Quarter Moon Face', shorts: ['first_quarter_moon_with_face'] },
    { emoji: '🌜', type: EmojiType.Nature, label: 'Last Quarter Moon Face', shorts: ['last_quarter_moon_with_face'] },
    { emoji: '☀️', type: EmojiType.Nature, label: 'un', shorts: ['sunny'] },
    { emoji: '🌝', type: EmojiType.Nature, label: 'Full Moon Face', shorts: ['full_moon_with_face'] },
    { emoji: '🌞', type: EmojiType.Nature, label: 'Sun With Face', shorts: ['sun_with_face'] },
    { emoji: '⭐', type: EmojiType.Nature, label: 'tar', shorts: ['star'] },
    { emoji: '🌟', type: EmojiType.Nature, label: 'Glowing Star', shorts: ['star2'] },
    { emoji: '🌠', type: EmojiType.Nature, label: 'Shooting Star', shorts: ['stars'] },
    { emoji: '☁️', type: EmojiType.Nature, label: 'loud', shorts: ['cloud'] },
    { emoji: '⛅', type: EmojiType.Nature, label: 'un Behind Cloud', shorts: ['partly_sunny'] },
    { emoji: '⛈️', type: EmojiType.Nature, label: 'loud With Lightning and Rain', shorts: [] },
    { emoji: '🌤️', type: EmojiType.Nature, label: 'Sun Behind Small Cloud', shorts: [] },
    { emoji: '🌥️', type: EmojiType.Nature, label: 'Sun Behind Large Cloud', shorts: [] },
    { emoji: '🌦️', type: EmojiType.Nature, label: 'Sun Behind Rain Cloud', shorts: [] },
    { emoji: '🌧️', type: EmojiType.Nature, label: 'Cloud With Rain', shorts: [] },
    { emoji: '🌨️', type: EmojiType.Nature, label: 'Cloud With Snow', shorts: [] },
    { emoji: '🌩️', type: EmojiType.Nature, label: 'Cloud With Lightning', shorts: [] },
    { emoji: '🌪️', type: EmojiType.Nature, label: 'Tornado', shorts: [] },
    { emoji: '🌫️', type: EmojiType.Nature, label: 'Fog', shorts: [] },
    { emoji: '🌬️', type: EmojiType.Nature, label: 'Wind Face', shorts: [] },
    { emoji: '🌈', type: EmojiType.Nature, label: 'Rainbow', shorts: ['rainbow'] },
    { emoji: '☂️', type: EmojiType.Nature, label: 'mbrella', shorts: [] },
    { emoji: '☔', type: EmojiType.Nature, label: 'mbrella With Rain Drops', shorts: ['umbrella'] },
    { emoji: '⚡', type: EmojiType.Nature, label: 'igh Voltage', shorts: ['zap'] },
    { emoji: '❄️', type: EmojiType.Nature, label: 'nowflake', shorts: ['snowflake'] },
    { emoji: '☃️', type: EmojiType.Nature, label: 'nowman', shorts: [] },
    { emoji: '⛄', type: EmojiType.Nature, label: 'nowman Without Snow', shorts: ['snowman'] },
    { emoji: '☄️', type: EmojiType.Nature, label: 'omet', shorts: [] },
    { emoji: '🔥', type: EmojiType.Nature, label: 'Fire', shorts: ['fire'] },
    { emoji: '💧', type: EmojiType.Nature, label: 'Droplet', shorts: ['droplet'] },
    { emoji: '🌊', type: EmojiType.Nature, label: 'Water Wave', shorts: ['ocean'] },
    { emoji: '🎄', type: EmojiType.Nature, label: 'Christmas Tree', shorts: ['christmas_tree'] },
    { emoji: '✨', type: EmojiType.Nature, label: 'parkles', shorts: ['sparkles'] },
    { emoji: '🎋', type: EmojiType.Nature, label: 'Tanabata Tree', shorts: ['tanabata_tree'] },
    { emoji: '🎍', type: EmojiType.Nature, label: 'Pine Decoration', shorts: ['bamboo'] },
];

export const SymbolsEmoji: EmojiItem[] = [
    { emoji: '💘', type: EmojiType.Symbols, label: 'Heart With Arrow', shorts: ['cupid'] },
    { emoji: '💝', type: EmojiType.Symbols, label: 'Heart With Ribbon', shorts: ['gift_heart'] },
    { emoji: '💖', type: EmojiType.Symbols, label: 'Sparkling Heart', shorts: ['sparkling_heart'] },
    { emoji: '💗', type: EmojiType.Symbols, label: 'Growing Heart', shorts: ['heartpulse'] },
    { emoji: '💓', type: EmojiType.Symbols, label: 'Beating Heart', shorts: ['heartbeat'] },
    { emoji: '💞', type: EmojiType.Symbols, label: 'Revolving Hearts', shorts: ['revolving_hearts'] },
    { emoji: '💕', type: EmojiType.Symbols, label: 'Two Hearts', shorts: ['two_hearts'] },
    { emoji: '💟', type: EmojiType.Symbols, label: 'Heart Decoration', shorts: ['heart_decoration'] },
    { emoji: '❣️', type: EmojiType.Symbols, label: 'eavy Heart Exclamation', shorts: [] },
    { emoji: '💔', type: EmojiType.Symbols, label: 'Broken Heart', shorts: ['broken_heart'] },
    { emoji: '❤️', type: EmojiType.Symbols, label: 'ed Heart', shorts: ['heart'] },
    { emoji: '🧡', type: EmojiType.Symbols, label: 'Orange Heart', shorts: [] },
    { emoji: '💛', type: EmojiType.Symbols, label: 'Yellow Heart', shorts: ['yellow_heart'] },
    { emoji: '💚', type: EmojiType.Symbols, label: 'Green Heart', shorts: ['green_heart'] },
    { emoji: '💙', type: EmojiType.Symbols, label: 'Blue Heart', shorts: ['blue_heart'] },
    { emoji: '💜', type: EmojiType.Symbols, label: 'Purple Heart', shorts: ['purple_heart'] },
    { emoji: '🖤', type: EmojiType.Symbols, label: 'Black Heart', shorts: [] },
    { emoji: '💯', type: EmojiType.Symbols, label: 'Hundred Points', shorts: ['100'] },
    { emoji: '💢', type: EmojiType.Symbols, label: 'Anger Symbol', shorts: ['anger'] },
    { emoji: '💬', type: EmojiType.Symbols, label: 'Speech Balloon', shorts: ['speech_balloon'] },
    { emoji: '👁️‍🗨️', type: EmojiType.Symbols, label: '‍🗨️ Eye in Speech Bubble', shorts: [] },
    { emoji: '🗯️', type: EmojiType.Symbols, label: 'Right Anger Bubble', shorts: [] },
    { emoji: '💭', type: EmojiType.Symbols, label: 'Thought Balloon', shorts: ['thought_balloon'] },
    { emoji: '💤', type: EmojiType.Symbols, label: 'Zzz', shorts: ['zzz'] },
    { emoji: '💮', type: EmojiType.Symbols, label: 'White Flower', shorts: ['white_flower'] },
    { emoji: '♨️', type: EmojiType.Symbols, label: 'ot Springs', shorts: ['hotsprings'] },
    { emoji: '💈', type: EmojiType.Symbols, label: 'Barber Pole', shorts: ['barber'] },
    { emoji: '🛑', type: EmojiType.Symbols, label: 'Stop Sign', shorts: [] },
    { emoji: '🕛', type: EmojiType.Symbols, label: 'Twelve O’Clock', shorts: ['clock12'] },
    { emoji: '🕧', type: EmojiType.Symbols, label: 'Twelve-Thirty', shorts: ['clock1230'] },
    { emoji: '🕐', type: EmojiType.Symbols, label: 'One O’Clock', shorts: ['clock1'] },
    { emoji: '🕜', type: EmojiType.Symbols, label: 'One-Thirty', shorts: ['clock130'] },
    { emoji: '🕑', type: EmojiType.Symbols, label: 'Two O’Clock', shorts: ['clock2'] },
    { emoji: '🕝', type: EmojiType.Symbols, label: 'Two-Thirty', shorts: ['clock230'] },
    { emoji: '🕒', type: EmojiType.Symbols, label: 'Three O’Clock', shorts: ['clock3'] },
    { emoji: '🕞', type: EmojiType.Symbols, label: 'Three-Thirty', shorts: ['clock330'] },
    { emoji: '🕓', type: EmojiType.Symbols, label: 'Four O’Clock', shorts: ['clock4'] },
    { emoji: '🕟', type: EmojiType.Symbols, label: 'Four-Thirty', shorts: ['clock430'] },
    { emoji: '🕔', type: EmojiType.Symbols, label: 'Five O’Clock', shorts: ['clock5'] },
    { emoji: '🕠', type: EmojiType.Symbols, label: 'Five-Thirty', shorts: ['clock530'] },
    { emoji: '🕕', type: EmojiType.Symbols, label: 'Six O’Clock', shorts: ['clock6'] },
    { emoji: '🕡', type: EmojiType.Symbols, label: 'Six-Thirty', shorts: ['clock630'] },
    { emoji: '🕖', type: EmojiType.Symbols, label: 'Seven O’Clock', shorts: ['clock7'] },
    { emoji: '🕢', type: EmojiType.Symbols, label: 'Seven-Thirty', shorts: ['clock730'] },
    { emoji: '🕗', type: EmojiType.Symbols, label: 'Eight O’Clock', shorts: ['clock8'] },
    { emoji: '🕣', type: EmojiType.Symbols, label: 'Eight-Thirty', shorts: ['clock830'] },
    { emoji: '🕘', type: EmojiType.Symbols, label: 'Nine O’Clock', shorts: ['clock9'] },
    { emoji: '🕤', type: EmojiType.Symbols, label: 'Nine-Thirty', shorts: ['clock930'] },
    { emoji: '🕙', type: EmojiType.Symbols, label: 'Ten O’Clock', shorts: ['clock10'] },
    { emoji: '🕥', type: EmojiType.Symbols, label: 'Ten-Thirty', shorts: ['clock1030'] },
    { emoji: '🕚', type: EmojiType.Symbols, label: 'Eleven O’Clock', shorts: ['clock11'] },
    { emoji: '🕦', type: EmojiType.Symbols, label: 'Eleven-Thirty', shorts: ['clock1130'] },
    { emoji: '🌀', type: EmojiType.Symbols, label: 'Cyclone', shorts: ['cyclone'] },
    { emoji: '♠️', type: EmojiType.Symbols, label: 'pade Suit', shorts: ['spades'] },
    { emoji: '♥️', type: EmojiType.Symbols, label: 'eart Suit', shorts: ['hearts'] },
    { emoji: '♦️', type: EmojiType.Symbols, label: 'iamond Suit', shorts: ['diamonds'] },
    { emoji: '♣️', type: EmojiType.Symbols, label: 'lub Suit', shorts: ['clubs'] },
    { emoji: '🃏', type: EmojiType.Symbols, label: 'Joker', shorts: ['black_joker'] },
    { emoji: '🀄', type: EmojiType.Symbols, label: 'Mahjong Red Dragon', shorts: ['mahjong'] },
    { emoji: '🎴', type: EmojiType.Symbols, label: 'Flower Playing Cards', shorts: ['flower_playing_cards'] },
    { emoji: '🔇', type: EmojiType.Symbols, label: 'Muted Speaker', shorts: ['mute'] },
    { emoji: '🔈', type: EmojiType.Symbols, label: 'Speaker Low Volume', shorts: ['speaker'] },
    { emoji: '🔉', type: EmojiType.Symbols, label: 'Speaker Medium Volume', shorts: ['sound'] },
    { emoji: '🔊', type: EmojiType.Symbols, label: 'Speaker High Volume', shorts: ['loud_sound'] },
    { emoji: '📢', type: EmojiType.Symbols, label: 'Loudspeaker', shorts: ['loudspeaker'] },
    { emoji: '📣', type: EmojiType.Symbols, label: 'Megaphone', shorts: ['mega'] },
    { emoji: '📯', type: EmojiType.Symbols, label: 'Postal Horn', shorts: ['postal_horn'] },
    { emoji: '🔔', type: EmojiType.Symbols, label: 'Bell', shorts: ['bell'] },
    { emoji: '🔕', type: EmojiType.Symbols, label: 'Bell With Slash', shorts: ['no_bell'] },
    { emoji: '🎵', type: EmojiType.Symbols, label: 'Musical Note', shorts: ['musical_note'] },
    { emoji: '🎶', type: EmojiType.Symbols, label: 'Musical Notes', shorts: ['notes'] },
    { emoji: '🏧', type: EmojiType.Symbols, label: 'ATM Sign', shorts: ['atm'] },
    { emoji: '🚮', type: EmojiType.Symbols, label: 'Litter in Bin Sign', shorts: ['put_litter_in_its_place'] },
    { emoji: '🚰', type: EmojiType.Symbols, label: 'Potable Water', shorts: ['potable_water'] },
    { emoji: '♿', type: EmojiType.Symbols, label: 'heelchair Symbol', shorts: ['wheelchair'] },
    { emoji: '🚹', type: EmojiType.Symbols, label: 'Men’s Room', shorts: ['mens'] },
    { emoji: '🚺', type: EmojiType.Symbols, label: 'Women’s Room', shorts: ['womens'] },
    { emoji: '🚻', type: EmojiType.Symbols, label: 'Restroom', shorts: ['restroom'] },
    { emoji: '🚼', type: EmojiType.Symbols, label: 'Baby Symbol', shorts: ['baby_symbol'] },
    { emoji: '🚾', type: EmojiType.Symbols, label: 'Water Closet', shorts: ['wc'] },
    { emoji: '⚠️', type: EmojiType.Symbols, label: 'arning', shorts: ['warning'] },
    { emoji: '🚸', type: EmojiType.Symbols, label: 'Children Crossing', shorts: ['children_crossing'] },
    { emoji: '⛔', type: EmojiType.Symbols, label: 'o Entry', shorts: ['no_entry'] },
    { emoji: '🚫', type: EmojiType.Symbols, label: 'Prohibited', shorts: ['no_entry_sign'] },
    { emoji: '🚳', type: EmojiType.Symbols, label: 'No Bicycles', shorts: ['no_bicycles'] },
    { emoji: '🚭', type: EmojiType.Symbols, label: 'No Smoking', shorts: ['no_smoking'] },
    { emoji: '🚯', type: EmojiType.Symbols, label: 'No Littering', shorts: ['do_not_litter'] },
    { emoji: '🚱', type: EmojiType.Symbols, label: 'Non-Potable Water', shorts: ['non-potable_water'] },
    { emoji: '🚷', type: EmojiType.Symbols, label: 'No Pedestrians', shorts: ['no_pedestrians'] },
    { emoji: '🔞', type: EmojiType.Symbols, label: 'No One Under Eighteen', shorts: ['underage'] },
    { emoji: '☢️', type: EmojiType.Symbols, label: 'adioactive', shorts: [] },
    { emoji: '☣️', type: EmojiType.Symbols, label: 'iohazard', shorts: [] },
    { emoji: '⬆️', type: EmojiType.Symbols, label: 'p Arrow', shorts: ['arrow_up'] },
    { emoji: '↗️', type: EmojiType.Symbols, label: 'p-Right Arrow', shorts: ['arrow_upper_right'] },
    { emoji: '➡️', type: EmojiType.Symbols, label: 'ight Arrow', shorts: ['arrow_right'] },
    { emoji: '↘️', type: EmojiType.Symbols, label: 'own-Right Arrow', shorts: ['arrow_lower_right'] },
    { emoji: '⬇️', type: EmojiType.Symbols, label: 'own Arrow', shorts: ['arrow_down'] },
    { emoji: '↙️', type: EmojiType.Symbols, label: 'own-Left Arrow', shorts: ['arrow_lower_left'] },
    { emoji: '⬅️', type: EmojiType.Symbols, label: 'eft Arrow', shorts: ['arrow_left'] },
    { emoji: '↖️', type: EmojiType.Symbols, label: 'p-Left Arrow', shorts: ['arrow_upper_left'] },
    { emoji: '↕️', type: EmojiType.Symbols, label: 'p-Down Arrow', shorts: ['arrow_up_down'] },
    { emoji: '↔️', type: EmojiType.Symbols, label: 'eft-Right Arrow', shorts: ['left_right_arrow'] },
    { emoji: '↩️', type: EmojiType.Symbols, label: 'ight Arrow Curving Left', shorts: ['leftwards_arrow_with_hook'] },
    { emoji: '↪️', type: EmojiType.Symbols, label: 'eft Arrow Curving Right', shorts: ['arrow_right_hook'] },
    { emoji: '⤴️', type: EmojiType.Symbols, label: 'ight Arrow Curving Up', shorts: ['arrow_heading_up'] },
    { emoji: '⤵️', type: EmojiType.Symbols, label: 'ight Arrow Curving Down', shorts: ['arrow_heading_down'] },
    { emoji: '🔃', type: EmojiType.Symbols, label: 'Clockwise Vertical Arrows', shorts: ['arrows_clockwise'] },
    {
        emoji: '🔄',
        type: EmojiType.Symbols,
        label: 'Counterclockwise Arrows Button',
        shorts: ['arrows_counterclockwise'],
    },
    { emoji: '🔙', type: EmojiType.Symbols, label: 'Back Arrow', shorts: ['back'] },
    { emoji: '🔚', type: EmojiType.Symbols, label: 'End Arrow', shorts: ['end'] },
    { emoji: '🔛', type: EmojiType.Symbols, label: 'On! Arrow', shorts: ['on'] },
    { emoji: '🔜', type: EmojiType.Symbols, label: 'Soon Arrow', shorts: ['soon'] },
    { emoji: '🔢', type: EmojiType.Symbols, label: 'Input Numbers', shorts: ['1234'] },
    { emoji: '🔣', type: EmojiType.Symbols, label: 'Input Symbols', shorts: ['symbols'] },
];

export const FoodsEmoji: EmojiItem[] = [
    { emoji: '🍇', type: EmojiType.Foods, label: 'Grapes', shorts: ['grapes'] },
    { emoji: '🍈', type: EmojiType.Foods, label: 'Melon', shorts: ['melon'] },
    { emoji: '🍉', type: EmojiType.Foods, label: 'Watermelon', shorts: ['watermelon'] },
    { emoji: '🍊', type: EmojiType.Foods, label: 'Tangerine', shorts: ['tangerine'] },
    { emoji: '🍋', type: EmojiType.Foods, label: 'Lemon', shorts: ['lemon'] },
    { emoji: '🍌', type: EmojiType.Foods, label: 'Banana', shorts: ['banana'] },
    { emoji: '🍍', type: EmojiType.Foods, label: 'Pineapple', shorts: ['pineapple'] },
    { emoji: '🍎', type: EmojiType.Foods, label: 'Red Apple', shorts: ['apple'] },
    { emoji: '🍏', type: EmojiType.Foods, label: 'Green Apple', shorts: ['green_apple'] },
    { emoji: '🍐', type: EmojiType.Foods, label: 'Pear', shorts: ['pear'] },
    { emoji: '🍑', type: EmojiType.Foods, label: 'Peach', shorts: ['peach'] },
    { emoji: '🍒', type: EmojiType.Foods, label: 'Cherries', shorts: ['cherries'] },
    { emoji: '🍓', type: EmojiType.Foods, label: 'Strawberry', shorts: ['strawberry'] },
    { emoji: '🥝', type: EmojiType.Foods, label: 'Kiwi Fruit', shorts: [] },
    { emoji: '🍅', type: EmojiType.Foods, label: 'Tomato', shorts: ['tomato'] },
    { emoji: '🥥', type: EmojiType.Foods, label: 'Coconut', shorts: [] },
    { emoji: '🥑', type: EmojiType.Foods, label: 'Avocado', shorts: [] },
    { emoji: '🍆', type: EmojiType.Foods, label: 'Eggplant', shorts: ['eggplant'] },
    { emoji: '🥔', type: EmojiType.Foods, label: 'Potato', shorts: [] },
    { emoji: '🥕', type: EmojiType.Foods, label: 'Carrot', shorts: [] },
    { emoji: '🌽', type: EmojiType.Foods, label: 'Ear of Corn', shorts: ['corn'] },
    { emoji: '🌶️', type: EmojiType.Foods, label: 'Hot Pepper', shorts: [] },
    { emoji: '🥒', type: EmojiType.Foods, label: 'Cucumber', shorts: [] },
    { emoji: '🥦', type: EmojiType.Foods, label: 'Broccoli', shorts: [] },
    { emoji: '🍄', type: EmojiType.Foods, label: 'Mushroom', shorts: ['mushroom'] },
    { emoji: '🥜', type: EmojiType.Foods, label: 'Peanuts', shorts: [] },
    { emoji: '🌰', type: EmojiType.Foods, label: 'Chestnut', shorts: ['chestnut'] },
    { emoji: '🍞', type: EmojiType.Foods, label: 'Bread', shorts: ['bread'] },
    { emoji: '🥐', type: EmojiType.Foods, label: 'Croissant', shorts: [] },
    { emoji: '🥖', type: EmojiType.Foods, label: 'Baguette Bread', shorts: [] },
    { emoji: '🥨', type: EmojiType.Foods, label: 'Pretzel', shorts: [] },
    { emoji: '🥞', type: EmojiType.Foods, label: 'Pancakes', shorts: [] },
    { emoji: '🧀', type: EmojiType.Foods, label: 'Cheese Wedge', shorts: [] },
    { emoji: '🍖', type: EmojiType.Foods, label: 'Meat on Bone', shorts: ['meat_on_bone'] },
    { emoji: '🍗', type: EmojiType.Foods, label: 'Poultry Leg', shorts: ['poultry_leg'] },
    { emoji: '🥩', type: EmojiType.Foods, label: 'Cut of Meat', shorts: [] },
    { emoji: '🥓', type: EmojiType.Foods, label: 'Bacon', shorts: [] },
    { emoji: '🍔', type: EmojiType.Foods, label: 'Hamburger', shorts: ['hamburger'] },
    { emoji: '🍟', type: EmojiType.Foods, label: 'French Fries', shorts: ['fries'] },
    { emoji: '🍕', type: EmojiType.Foods, label: 'Pizza', shorts: ['pizza'] },
    { emoji: '🌭', type: EmojiType.Foods, label: 'Hot Dog', shorts: [] },
    { emoji: '🥪', type: EmojiType.Foods, label: 'Sandwich', shorts: [] },
    { emoji: '🌮', type: EmojiType.Foods, label: 'Taco', shorts: [] },
    { emoji: '🌯', type: EmojiType.Foods, label: 'Burrito', shorts: [] },
    { emoji: '🥙', type: EmojiType.Foods, label: 'Stuffed Flatbread', shorts: [] },
    { emoji: '🍳', type: EmojiType.Foods, label: 'Cooking', shorts: ['egg'] },
    { emoji: '🥘', type: EmojiType.Foods, label: 'Shallow Pan of Food', shorts: [] },
    { emoji: '🍲', type: EmojiType.Foods, label: 'Pot of Food', shorts: ['stew'] },
    { emoji: '🥣', type: EmojiType.Foods, label: 'Bowl With Spoon', shorts: [] },
    { emoji: '🥗', type: EmojiType.Foods, label: 'Green Salad', shorts: [] },
    { emoji: '🍿', type: EmojiType.Foods, label: 'Popcorn', shorts: [] },
    { emoji: '🥫', type: EmojiType.Foods, label: 'Canned Food', shorts: [] },
    { emoji: '🍱', type: EmojiType.Foods, label: 'Bento Box', shorts: ['bento'] },
    { emoji: '🍘', type: EmojiType.Foods, label: 'Rice Cracker', shorts: ['rice_cracker'] },
    { emoji: '🍙', type: EmojiType.Foods, label: 'Rice Ball', shorts: ['rice_ball'] },
    { emoji: '🍚', type: EmojiType.Foods, label: 'Cooked Rice', shorts: ['rice'] },
    { emoji: '🍛', type: EmojiType.Foods, label: 'Curry Rice', shorts: ['curry'] },
    { emoji: '🍜', type: EmojiType.Foods, label: 'Steaming Bowl', shorts: ['ramen'] },
    { emoji: '🍝', type: EmojiType.Foods, label: 'Spaghetti', shorts: ['spaghetti'] },
    { emoji: '🍠', type: EmojiType.Foods, label: 'Roasted Sweet Potato', shorts: ['sweet_potato'] },
    { emoji: '🍢', type: EmojiType.Foods, label: 'Oden', shorts: ['oden'] },
    { emoji: '🍣', type: EmojiType.Foods, label: 'Sushi', shorts: ['sushi'] },
    { emoji: '🍤', type: EmojiType.Foods, label: 'Fried Shrimp', shorts: ['fried_shrimp'] },
    { emoji: '🍥', type: EmojiType.Foods, label: 'Fish Cake With Swirl', shorts: ['fish_cake'] },
    { emoji: '🍡', type: EmojiType.Foods, label: 'Dango', shorts: ['dango'] },
    { emoji: '🥟', type: EmojiType.Foods, label: 'Dumpling', shorts: [] },
    { emoji: '🥠', type: EmojiType.Foods, label: 'Fortune Cookie', shorts: [] },
    { emoji: '🥡', type: EmojiType.Foods, label: 'Takeout Box', shorts: [] },
    { emoji: '🍦', type: EmojiType.Foods, label: 'Soft Ice Cream', shorts: ['icecream'] },
    { emoji: '🍧', type: EmojiType.Foods, label: 'Shaved Ice', shorts: ['shaved_ice'] },
    { emoji: '🍨', type: EmojiType.Foods, label: 'Ice Cream', shorts: ['ice_cream'] },
    { emoji: '🍩', type: EmojiType.Foods, label: 'Doughnut', shorts: ['doughnut'] },
    { emoji: '🍪', type: EmojiType.Foods, label: 'Cookie', shorts: ['cookie'] },
    { emoji: '🎂', type: EmojiType.Foods, label: 'Birthday Cake', shorts: ['birthday'] },
    { emoji: '🍰', type: EmojiType.Foods, label: 'Shortcake', shorts: ['cake'] },
    { emoji: '🥧', type: EmojiType.Foods, label: 'Pie', shorts: [] },
    { emoji: '🍫', type: EmojiType.Foods, label: 'Chocolate Bar', shorts: ['chocolate_bar'] },
    { emoji: '🍬', type: EmojiType.Foods, label: 'Candy', shorts: ['candy'] },
    { emoji: '🍭', type: EmojiType.Foods, label: 'Lollipop', shorts: ['lollipop'] },
    { emoji: '🍮', type: EmojiType.Foods, label: 'Custard', shorts: ['custard'] },
    { emoji: '🍯', type: EmojiType.Foods, label: 'Honey Pot', shorts: ['honey_pot'] },
    { emoji: '🍼', type: EmojiType.Foods, label: 'Baby Bottle', shorts: ['baby_bottle'] },
    { emoji: '🥛', type: EmojiType.Foods, label: 'Glass of Milk', shorts: [] },
    { emoji: '☕', type: EmojiType.Foods, label: 'ot Beverage', shorts: ['coffee'] },
    { emoji: '🍵', type: EmojiType.Foods, label: 'Teacup Without Handle', shorts: ['tea'] },
    { emoji: '🍶', type: EmojiType.Foods, label: 'Sake', shorts: ['sake'] },
    { emoji: '🍾', type: EmojiType.Foods, label: 'Bottle With Popping Cork', shorts: [] },
    { emoji: '🍷', type: EmojiType.Foods, label: 'Wine Glass', shorts: ['wine_glass'] },
    { emoji: '🍸', type: EmojiType.Foods, label: 'Cocktail Glass', shorts: ['cocktail'] },
    { emoji: '🍹', type: EmojiType.Foods, label: 'Tropical Drink', shorts: ['tropical_drink'] },
    { emoji: '🍺', type: EmojiType.Foods, label: 'Beer Mug', shorts: ['beer'] },
    { emoji: '🍻', type: EmojiType.Foods, label: 'Clinking Beer Mugs', shorts: ['beers'] },
    { emoji: '🥂', type: EmojiType.Foods, label: 'Clinking Glasses', shorts: [] },
    { emoji: '🥃', type: EmojiType.Foods, label: 'Tumbler Glass', shorts: [] },
    { emoji: '🥤', type: EmojiType.Foods, label: 'Cup With Straw', shorts: [] },
    { emoji: '🥢', type: EmojiType.Foods, label: 'Chopsticks', shorts: [] },
    { emoji: '🍽️', type: EmojiType.Foods, label: 'Fork and Knife With Plate', shorts: [] },
    { emoji: '🍴', type: EmojiType.Foods, label: 'Fork and Knife', shorts: ['fork_and_knife'] },
    { emoji: '🥄', type: EmojiType.Foods, label: 'Spoon', shorts: [] },
];

export default [...PeopleEmoji, ...NatureEmoji, ...FoodsEmoji, ...SymbolsEmoji];
